# Generated by Django 2.0.6 on 2018-06-26 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mood',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Mood'),
            preserve_default=False,
        ),
    ]
