# Generated by Django 2.0.6 on 2018-06-26 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='which_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='user_who_followed', to='main.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Mood'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_who_disliked',
            field=models.ManyToManyField(blank=True, related_name='user_who_disliked', to='main.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_who_liked',
            field=models.ManyToManyField(blank=True, related_name='user_who_liked', to='main.User'),
        ),
    ]
